spring.application.name=finance
spring.datasource.url=jdbc:postgresql://192.168.55.103:5432/finance_tracker
spring.datasource.username=finance_user
spring.datasource.password=Fin@nce@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
jwt.secret=DPFmebD3EY2gMsS5y8SC6WpWvwkktSWj